workflows:
  android:
    name: 'Android'
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      groups:
        - qbot
    scripts:
      - name: 'Setup keystore'
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
      - name: 'Installing Node'
        script: |
          npm install
          npm ci
          cvm install 9.0.0
          cvm use 9.0.0
      - name: 'Running Vite Build'
        script: |
          npm run build
      - name: 'Moving to build directory'
        script: |
          cd build
      - name: 'Installing Cordova SDK'
        script: |
          npm install cordova@latest
      - name: 'Setup Android CordovaSDK project...'
        script: |
          cordova platform remove android --no-save
          cordova platform add android \
          --confirm \
          --no-interactive \
          --noresources
      - name: 'Building Android app...'
        script: cordova build android
      - name: 'Signing APK...'
        script: |
          APK_PATH=$(find platforms/android/app/build/outputs/apk/debug -name "*.apk" | head -1)
          jarsigner \
          -sigalg SHA1withRSA \
          -digestalg SHA1 \
          -keystore $CM_KEYSTORE_PATH \
          -storepass $CM_KEYSTORE_PASSWORD \
          -keypass $CM_KEY_PASSWORD \
          $APK_PATH $CM_KEY_ALIAS
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
